name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Build or deploy steps
        run: echo "Esegui il build o il deploy qui..."
